// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlaAC069scJDhbvoxcm5hV9dFOOzFwqb8',
    appId: '1:711979024554:web:275bd3ca5f5c26985990d3',
    messagingSenderId: '711979024554',
    projectId: 'tringconnect-2022',
    authDomain: 'tringconnect-2022.firebaseapp.com',
    storageBucket: 'tringconnect-2022.appspot.com',
    measurementId: 'G-EKV90D678K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQJT31cITnOtu0oO_vTm1HoDyBIV07qw',
    appId: '1:711979024554:android:4b7f117c6df9c3c65990d3',
    messagingSenderId: '711979024554',
    projectId: 'tringconnect-2022',
    storageBucket: 'tringconnect-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eO-mQb9HcjsXKDZn4OgTjFuYOJBYBtc',
    appId: '1:711979024554:ios:0ed602094f61cfdb5990d3',
    messagingSenderId: '711979024554',
    projectId: 'tringconnect-2022',
    storageBucket: 'tringconnect-2022.appspot.com',
    iosClientId: '711979024554-je41vmllfgja9t5qkc278psudoltv1te.apps.googleusercontent.com',
    iosBundleId: 'com.tringapps.tringconnect.tringconnect',
  );
}
